---
- block:
    - debug: msg='Check current configuration'
    # configure
    - include: tasks.yml
    - include: tasks-without-rescue.yml
    - block:
        # Testing install
        - debug: msg='Launch install'
        - command: /bin/false
        # task would failed before
        - debug: msg='Normally not executed'
      rescue:
        - debug: msg='Rescue on install'
  rescue:
    - include: rollback.yml