- name: Check accessible
  action: ping

- name: Test already installed
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ tmp_path }}"
    - /toto

- name:
  command: echo Configure