---
- block:
    - name: Test already installed
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ tmp_path }}"
        - /toto
    - name: Check accessible
      action: ping
    - name:
      command: echo Configure
  rescue:
    - command: echo "Rollback configure"
    - debug: msg='Rescue mode on configure'